var num = 2.5;
var result= Math.floor(num);
var result2= Math.ceil(num);
var result3 = Math.round(num);
var dice = Math.random()*6;
var output = Math.round(dice);
console.log("Floor:",result);
console.log("Ceil:",result2);
console.log("Round:",result3);
console.log("Random:",dice);
console.log("Round Random:", output);